---
# tasks file for install-ufw

- name: Update apt 
  apt: update_cache=yes cache_valid_time=3600

- name: Update all packages to the latest version
  apt: upgrade=dist
  register: upgrade

- name: Install UFW
  apt: name=ufw state=present
  register: ufw_install

- name: Enable UFW
  ufw: state=enabled policy=allow logging=on
  register: ufw_enable

- name: Reboot server
  command: /sbin/reboot
  when: upgrade.changed or ufw_install.changed or ufw_enable.changed

- name: Wait for the server to finish rebooting
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 delay=60 timeout=300
  when: upgrade.changed or ufw_install.changed or ufw_enable.changed

- name: Get uptime
  command: uptime
  register: uptime
  changed_when: false

- name: Show uptime from hostvars (invalid after reboot)
  debug: var=ohai_uptime

- name: Show uptime from command
  debug: var=uptime.stdout